name = "veil-frontend"
main = "./dist/_worker.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "veil-db"
database_id = "17141d5e-9cbc-4dce-ab8e-313c5ef96960"

[vars]

[build]
command = "npm run build"
