name = "veil-email-worker"
main = "src/index.js"
compatibility_date = "2025-04-01"

[[d1_databases]]
binding = "DB"
database_name = "veil-db"
database_id = "17141d5e-9cbc-4dce-ab8e-313c5ef96960"

[vars]

[limits]
email_minutes = 100
